import { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { BeforeAfterSlider } from './BeforeAfterSlider'
import { Download, Edit3, Bookmark, Maximize2, X } from 'lucide-react'

type ResultCardProps = {
    imageUrl: string
    modelName: string
    originalImageUrl?: string
    onSave?: () => void
    onRevise?: () => void
    onDownload?: () => void
    saving?: boolean
}

export function ResultCard({
    imageUrl,
    modelName,
    originalImageUrl,
    onSave,
    onRevise,
    onDownload,
    saving = false,
}: ResultCardProps) {
    const [showComparison, setShowComparison] = useState(false)
    const [isFullscreen, setIsFullscreen] = useState(false)
    const [isHovered, setIsHovered] = useState(false)
    const [mounted, setMounted] = useState(false)

    // Check if we're mounted (client-side only)
    useEffect(() => {
        setMounted(true)
    }, [])

    // Handle ESC key to close fullscreen
    useEffect(() => {
        if (!isFullscreen) return

        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === 'Escape') {
                setIsFullscreen(false)
            }
        }

        // Prevent body scroll when fullscreen is open
        document.body.style.overflow = 'hidden'
        window.addEventListener('keydown', handleKeyDown)

        return () => {
            document.body.style.overflow = 'unset'
            window.removeEventListener('keydown', handleKeyDown)
        }
    }, [isFullscreen])

    const handleDownload = async () => {
        if (onDownload) return onDownload()

        try {
            const response = await fetch(imageUrl)
            const blob = await response.blob()
            const url = URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `BildOro-${modelName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.jpg`
            a.click()
            URL.revokeObjectURL(url)
        } catch (error) {
            console.error('Download failed:', error)
        }
    }

    const handleFullscreen = () => {
        setIsFullscreen(true)
    }

    const handleCloseFullscreen = () => {
        setIsFullscreen(false)
    }

    return (
        <>
            <div
                className="group relative border border-border rounded-xl bg-surface overflow-hidden shadow-md hover:shadow-2xl transition-all duration-300 w-full"
                onMouseEnter={() => setIsHovered(true)}
                onMouseLeave={() => setIsHovered(false)}
            >
                {/* Compact header */}
                <div className="flex items-center justify-between px-3 py-2.5 border-b border-border bg-surface/80 backdrop-blur-sm relative z-10">
                    <div className="font-semibold text-xs text-text flex items-center gap-2">
                        <span className="inline-block w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                        {modelName}
                    </div>
                    {originalImageUrl && (
                        <button
                            onClick={() => setShowComparison(!showComparison)}
                            className="text-xs font-medium text-primary hover:text-primary-dark transition-colors px-2 py-1 rounded hover:bg-primary/10"
                        >
                            {showComparison ? 'Result' : 'Compare'}
                        </button>
                    )}
                </div>

                {/* Image / Comparison Container - MAXIMIZED */}
                <div
                    className="relative w-full overflow-hidden bg-black/5"
                    style={{ aspectRatio: '1 / 1' }}
                >
                    {showComparison && originalImageUrl ? (
                        <div className="w-full h-full">
                            <BeforeAfterSlider
                                beforeImage={originalImageUrl}
                                afterImage={imageUrl}
                                beforeLabel="Original"
                                afterLabel="Generated"
                            />
                        </div>
                    ) : (
                        <div className="relative w-full h-full cursor-pointer group/image" onClick={handleFullscreen}>
                            {/* Image with zoom effect */}
                            <img
                                src={imageUrl}
                                alt={`Generated by ${modelName}`}
                                className={`object-cover w-full h-full transition-transform duration-700 ease-out ${
                                    isHovered ? 'scale-110' : 'scale-100'
                                }`}
                            />
                            
                            {/* Hover overlay with gradient */}
                            <div
                                className={`absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent transition-opacity duration-300 ${
                                    isHovered ? 'opacity-100' : 'opacity-0'
                                }`}
                            >
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <div className="bg-white/95 backdrop-blur-sm text-black px-4 py-2 rounded-full text-xs font-medium shadow-xl transform transition-transform duration-300 group-hover/image:scale-105">
                                        Click to enlarge
                                    </div>
                                </div>
                            </div>

                            {/* Corner gradient accents */}
                            <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-br from-primary/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 blur-2xl pointer-events-none" />
                            <div className="absolute bottom-0 left-0 w-24 h-24 bg-gradient-to-tr from-primary/30 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 blur-2xl pointer-events-none" />
                        </div>
                    )}
                </div>

                {/* Compact action bar */}
                <div className="flex justify-between items-center gap-1 px-2 py-2 border-t border-border bg-surface/80 backdrop-blur-sm">
                    <button
                        onClick={handleFullscreen}
                        title="View Fullscreen"
                        className="flex-1 flex items-center justify-center gap-1.5 text-muted-foreground hover:text-primary hover:bg-primary/5 rounded-lg px-2 py-2 transition-all duration-200 hover:scale-105 active:scale-95"
                    >
                        <Maximize2 className="size-4" />
                        <span className="text-xs font-medium hidden md:inline">View</span>
                    </button>
                    
                    {onRevise && (
                        <button
                            onClick={onRevise}
                            title="Edit / Revise"
                            className="flex-1 flex items-center justify-center gap-1.5 text-muted-foreground hover:text-primary hover:bg-primary/5 rounded-lg px-2 py-2 transition-all duration-200 hover:scale-105 active:scale-95"
                        >
                            <Edit3 className="size-4" />
                            <span className="text-xs font-medium hidden md:inline">Edit</span>
                        </button>
                    )}
                    
                    <button
                        onClick={handleDownload}
                        title="Download"
                        className="flex-1 flex items-center justify-center gap-1.5 text-muted-foreground hover:text-primary hover:bg-primary/5 rounded-lg px-2 py-2 transition-all duration-200 hover:scale-105 active:scale-95"
                    >
                        <Download className="size-4" />
                        <span className="text-xs font-medium hidden md:inline">Save</span>
                    </button>
                    
                    {onSave && (
                        <button
                            onClick={onSave}
                            disabled={saving}
                            title={saving ? 'Saving...' : 'Save to Gallery'}
                            className={`flex-1 flex items-center justify-center gap-1.5 rounded-lg px-2 py-2 transition-all duration-200 ${
                                saving
                                    ? 'opacity-50 cursor-not-allowed text-muted-foreground'
                                    : 'text-muted-foreground hover:text-primary hover:bg-primary/5 hover:scale-105 active:scale-95'
                            }`}
                        >
                            <Bookmark className={`size-4 ${saving ? 'animate-pulse' : ''}`} />
                            <span className="text-xs font-medium hidden md:inline">
                                {saving ? 'Saving...' : 'Gallery'}
                            </span>
                        </button>
                    )}
                </div>

                {/* Glow effect on hover */}
                <div
                    className={`absolute inset-0 rounded-xl transition-opacity duration-500 pointer-events-none ${
                        isHovered ? 'opacity-100' : 'opacity-0'
                    }`}
                    style={{
                        boxShadow: '0 0 60px rgba(212, 175, 55, 0.4), inset 0 0 40px rgba(212, 175, 55, 0.15)',
                    }}
                />
            </div>

            {/* Fullscreen Modal - Uses createPortal to render at body level */}
            {mounted && isFullscreen && createPortal(
                <div
                    className="fixed inset-0 z-[9999] bg-black/98 flex items-center justify-center animate-fade-in"
                    onClick={handleCloseFullscreen}
                    style={{ margin: 0, padding: 0 }}
                >
                    {/* Close button */}
                    <button
                        onClick={handleCloseFullscreen}
                        className="absolute top-4 right-4 md:top-6 md:right-6 text-white/90 hover:text-white transition-all bg-black/60 hover:bg-primary rounded-full p-2.5 md:p-3 backdrop-blur-sm z-50 hover:scale-110 active:scale-95"
                        title="Close (ESC)"
                    >
                        <X className="size-6 md:size-7" />
                    </button>

                    {/* Image container - truly centered and maximized */}
                    <div className="relative w-full h-full flex items-center justify-center p-4 md:p-8">
                        <img
                            src={imageUrl}
                            alt={`Generated by ${modelName}`}
                            className="max-w-full max-h-full w-auto h-auto object-contain animate-scale-in"
                            style={{ maxHeight: 'calc(100vh - 8rem)' }}
                            onClick={(e) => e.stopPropagation()}
                        />
                    </div>

                    {/* Model name badge - bottom center */}
                    <div className="absolute bottom-4 md:bottom-8 left-1/2 -translate-x-1/2 bg-black/80 backdrop-blur-md text-white px-4 md:px-6 py-2 md:py-3 rounded-full border border-white/20 shadow-2xl z-50">
                        <div className="flex items-center gap-2 md:gap-3">
                            <span className="inline-block w-1.5 md:w-2 h-1.5 md:h-2 rounded-full bg-primary animate-pulse"></span>
                            <span className="font-semibold text-sm md:text-base">{modelName}</span>
                        </div>
                    </div>

                    {/* Action buttons - top left */}
                    <div className="absolute top-4 left-4 md:top-6 md:left-6 flex gap-2 md:gap-3 z-50">
                        {onRevise && (
                            <button
                                onClick={(e) => {
                                    e.stopPropagation()
                                    onRevise()
                                    handleCloseFullscreen()
                                }}
                                className="bg-black/60 hover:bg-primary backdrop-blur-sm text-white rounded-full p-2.5 md:p-3 transition-all hover:scale-110 active:scale-95"
                                title="Edit / Revise"
                            >
                                <Edit3 className="size-4 md:size-5" />
                            </button>
                        )}
                        <button
                            onClick={(e) => {
                                e.stopPropagation()
                                handleDownload()
                            }}
                            className="bg-black/60 hover:bg-primary backdrop-blur-sm text-white rounded-full p-2.5 md:p-3 transition-all hover:scale-110 active:scale-95"
                            title="Download"
                        >
                            <Download className="size-4 md:size-5" />
                        </button>
                        {onSave && (
                            <button
                                onClick={(e) => {
                                    e.stopPropagation()
                                    onSave()
                                }}
                                disabled={saving}
                                className={`backdrop-blur-sm text-white rounded-full p-2.5 md:p-3 transition-all ${
                                    saving
                                        ? 'bg-black/40 cursor-not-allowed opacity-50'
                                        : 'bg-black/60 hover:bg-primary hover:scale-110 active:scale-95'
                                }`}
                                title={saving ? 'Saving...' : 'Save to Gallery'}
                            >
                                <Bookmark className={`size-4 md:size-5 ${saving ? 'animate-pulse' : ''}`} />
                            </button>
                        )}
                    </div>
                </div>,
                document.body
            )}
        </>
    )
}