import { useState } from 'react'
import { BeforeAfterSlider } from './BeforeAfterSlider'
import { Download, Edit3, Bookmark, Maximize2, X } from 'lucide-react'

type ResultCardProps = {
    imageUrl: string
    modelName: string
    originalImageUrl?: string
    onSave?: () => void
    onRevise?: () => void
    onDownload?: () => void
    saving?: boolean
}

export function ResultCard({
    imageUrl,
    modelName,
    originalImageUrl,
    onSave,
    onRevise,
    onDownload,
    saving = false,
}: ResultCardProps) {
    const [showComparison, setShowComparison] = useState(false)
    const [isFullscreen, setIsFullscreen] = useState(false)

    const handleDownload = async () => {
        if (onDownload) return onDownload()

        try {
            const response = await fetch(imageUrl)
            const blob = await response.blob()
            const url = URL.createObjectURL(blob)
            const a = document.createElement('a')
            a.href = url
            a.download = `BildOro-${modelName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.jpg`
            a.click()
            URL.revokeObjectURL(url)
        } catch (error) {
            console.error('Download failed:', error)
        }
    }

    const handleFullscreen = () => {
        setIsFullscreen(true)
    }

    const handleCloseFullscreen = () => {
        setIsFullscreen(false)
    }

    return (
        <>
            <div className="border border-border rounded-xl bg-background overflow-hidden shadow-sm hover:shadow-md transition-shadow w-full">
                {/* Header */}
                <div className="flex items-center justify-between p-3 border-b border-border">
                    <div className="font-medium text-sm text-text">{modelName}</div>
                    {originalImageUrl && (
                        <button
                            onClick={() => setShowComparison(!showComparison)}
                            className="text-xs text-primary hover:underline"
                        >
                            {showComparison ? 'Show Result' : 'Compare'}
                        </button>
                    )}
                </div>

                {/* Image / Comparison - fills full width */}
                <div className="bg-background relative w-full" style={{ aspectRatio: '1 / 1' }}>
                    {showComparison && originalImageUrl ? (
                        <BeforeAfterSlider
                            beforeImage={originalImageUrl}
                            afterImage={imageUrl}
                            beforeLabel="Original"
                            afterLabel="Generated"
                        />
                    ) : (
                        <img
                            src={imageUrl}
                            alt={`Generated by ${modelName}`}
                            className="object-cover w-full h-full cursor-pointer"
                            onClick={handleFullscreen}
                        />
                    )}
                </div>

                {/* Action bar */}
                <div className="flex justify-end items-center gap-3 p-3 border-t border-border">
                    <button
                        onClick={handleFullscreen}
                        title="View Fullscreen"
                        className="text-muted-foreground hover:text-primary cursor-pointer transition-colors"
                    >
                        <Maximize2 className="size-5" />
                    </button>
                    {onRevise && (
                        <button
                            onClick={onRevise}
                            title="Edit / Revise"
                            className="text-muted-foreground hover:text-primary cursor-pointer transition-colors"
                        >
                            <Edit3 className="size-5" />
                        </button>
                    )}
                    <button
                        onClick={handleDownload}
                        title="Download"
                        className="text-muted-foreground hover:text-primary cursor-pointer transition-colors"
                    >
                        <Download className="size-5" />
                    </button>
                    {onSave && (
                        <button
                            onClick={onSave}
                            disabled={saving}
                            title={saving ? 'Saving...' : 'Save to Gallery'}
                            className={`text-muted-foreground hover:text-primary cursor-pointer transition-colors ${
                                saving ? 'opacity-50 cursor-not-allowed' : ''
                            }`}
                        >
                            <Bookmark className="size-5" />
                        </button>
                    )}
                </div>
            </div>

            {/* Fullscreen Modal */}
            {isFullscreen && (
                <div
                    className="fixed inset-0 z-50 bg-black/95 flex items-center justify-center p-4"
                    onClick={handleCloseFullscreen}
                >
                    <button
                        onClick={handleCloseFullscreen}
                        className="absolute top-4 right-4 text-white hover:text-gray-300 transition-colors"
                        title="Close"
                    >
                        <X className="size-8" />
                    </button>
                    <div className="relative max-w-7xl max-h-full w-full h-full flex items-center justify-center">
                        <img
                            src={imageUrl}
                            alt={`Generated by ${modelName}`}
                            className="max-w-full max-h-full object-contain"
                            onClick={(e) => e.stopPropagation()}
                        />
                    </div>
                    <div className="absolute bottom-4 left-1/2 -translate-x-1/2 bg-black/70 text-white px-4 py-2 rounded-lg">
                        {modelName}
                    </div>
                </div>
            )}
        </>
    )
}